### PR TITLE
Add redis sentinel support

### PR DESCRIPTION
**Pull request by anyili**
Try to fix https://github.com/redis/redis-om-spring/issues/227
Tested in the cluster and locally.

### CODE REVIEW

**Comment by anyili** [comment]
Jedis 4.3.2 didn't have SentinelPooled, so I have to cherry pick the code from Jedis 4.4.3

**Comment by shannonantony** [comment]
thanks for your effort. Will it be part of the next release. thanks again.

**Comment by bsbodden** [comment]
I want to check with the Jedis maintainers first to see if we can avoid the extra code

**Comment by anyili** [comment]
if you upgrade to Jedis 4.4.3, it should come with those two classes. It will compile, but I run into some troubles to connect to redis. I think om model is not quite compatible with Jedis 4.4.3. And Spring boot depends on Jedis 4.3. So user should have force resolve to Jedis 4.4.3 in their pom.xml or build.gradle. It is not ideal neither

**Comment by bsbodden** [comment]
@anyili Anyi, can you post your test rig for this change? I want to write an integration test, possibly with TestContainers before we merge this.

**Comment by lucasleon2107** [comment]
Hi @bsbodden, does the library support Sentinel in its latest version (0.8.4)?

**Comment by lucasleon2107** [comment]
This is what I get in the logs btw

```
2023-07-10T23:04:18.529Z  INFO 1 --- [           main] redis.clients.jedis.JedisSentinelPool    : Redis master running at IP:PORT, starting Sentinel listeners...
2023-07-10T23:04:18.531Z  INFO 1 --- [           main] redis.clients.jedis.JedisSentinelPool    : Created JedisSentinelPool to IP:PORT
2023-07-10T23:04:22.415Z  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
2023-07-10T23:04:23.217Z  INFO 1 --- [           main] c.r.om.spring.RedisModulesConfiguration  : Creating Indexes......
2023-07-10T23:04:23.720Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found 1 @Document annotated Beans...
2023-07-10T23:04:23.720Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @JSON annotated class: UserHash
2023-07-10T23:04:23.721Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Indexed annotation on field of type: class java.lang.String
2023-07-10T23:04:23.722Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Indexed annotation on field of type: class java.lang.String
2023-07-10T23:04:23.811Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Searchable annotation on field of type: class java.lang.String
2023-07-10T23:04:23.813Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Searchable annotation on field of type: class java.lang.String
2023-07-10T23:04:23.813Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Indexed annotation on field of type: class java.lang.String
2023-07-10T23:04:23.813Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Indexed annotation on field of type: class java.lang.String
2023-07-10T23:04:23.813Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found @Indexed annotation on field of type: class java.lang.String
2023-07-10T23:04:23.817Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Using entity prefix 'UserHash:' as keyspace for type : class UserHash
2023-07-10T23:04:23.821Z  WARN 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Skipping index creation for UserHashIdx because Failed to connect to any host resolved for DNS name.
2023-07-10T23:04:24.015Z  INFO 1 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found 0 @RedisHash annotated Beans...
2023-07-10T23:04:24.215Z  INFO 1 --- [           main]  ApplicationKt       : Started ApplicationKt in 20.992 seconds (process running for 23.324)
```
The logs say that the application has started but in reality it stays in an unhealthy state.

I'm using Redis OM 0.8.4 and Jedis 4.4.3, but it also happens with the default Jedis that comes with Redis OM 0.8.4 and 0.8.2

I have a local sentinel deployment and it works fine with that, but with the Sentinel that is deployed on K8s this happens

**Comment by lucasleon2107** [comment]
Also, make sure to test this in a container-to-container scenario. I have a local sentinel deployment, and when I test the connection from my local machine to the sentinel container it works, but not when I deploy a service with Redis OM in a container and try to connect to the Sentinel container.

This is the compose file I'm using:

```
version: '3'

services:
  redis-master:
    image: redis/redis-stack-server
    container_name: redis-master
    ports:
      - 6379:6379
  redis-sentinel:
    image: redis:6.2.6-alpine
    container_name: redis-sentinel
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    depends_on:
      - redis-master
    volumes:
      - ./:/usr/local/etc/redis
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
```

**Comment by bsbodden** [comment]
Closing this PR and pushing a new one since I don't have write access to the fork

**Pull request closed without merging**
