### PR TITLE
feature: adds Redis sentinel support (resolves gh-227)

### PR DESCRIPTION
**Pull request by bsbodden**
- Retrieves UnifiedJedis from Spring Data Redis' RedisSentinelConfiguration
- Add TestContainers Sentinel Base Abstract TestCase

### CODE REVIEW

**Comment by bsbodden** [comment]
Spring Data Redis 3.2 will have Jedis 4.4.3 at which point this PR can be refactored

**Comment by shannonantony** [comment]
@bsbodden Just curious to know when will you be releasing Sentinel support for spring-redis-om. thanks Jay

**Comment by guos** [comment]
the same require since om not support cluster yet, then sentinel will be another choice

**Comment by bsbodden** [comment]
> @bsbodden Just curious to know when will you be releasing Sentinel support for spring-redis-om. thanks Jay

I have to wait for Spring Data Redis to up their Jedis version. I'll check to see where they are with it and if they have I'll merge. Thanks for the patience.

**Comment by shannonantony** [comment]
@bsbodden  Is it possible to do any work around solution for the time being? If so, what are the work around steps I need to follow to support sentinel?

thanks for your support

Jay

**Comment by bsbodden** [comment]
Included in Spring 3.2 PR

**Pull request closed without merging**
