### PR TITLE
release: release 0.6.0

### PR DESCRIPTION
**Pull request by bsbodden**
This PR buttons up the 0.6.0 release. Ups POM versions, apply SonarLint refactoring suggestions:

```
* 358d474 - refactor: clean up the wording on metamodel generator messages
* 4199a64 - ci: update wordlist for spellchecker action
* 92c821c - docs: add Spring Data Redis dependent version to README
* 704834f - refactor: constructors of an "abstract" class should not be declared "public" (SonarLint java:S5993) 
* 0a18374 - fix: second class type in Pair not properly declared in getFirstGetter
* 7ea1a46 - refactor: optional value should only be accessed after calling isPresent() (SonarLint java:S3655)
* 7556c47 - refactor: "@Override" should be used on overriding and implementing methods (SonarLint java:S1161)
* 3bdc48b - refactor: utility classes should not have public constructors (SonarLint java:S1118)
* b79cc9c - refactor: deprecated code should be removed (java:S1133)
* 31370ae - refactor: "equals(Object obj)" and "hashCode()" should be overridden in pairs (SonarLint java:S1206)
* e67a72c - refactor: boxing and unboxing should not be immediately reversed (SonarLint java:S2153)
* b5ba884 - refactor: "equals(Object obj)" should be overridden along with the "compareTo(T obj)" method (SonarLint java:S1210)
* ab26885 - refactor: boxed "Boolean" should be avoided in boolean expressions (SonarLint java:S5411)
* a2e1b19 - refactor: Strings should not be concatenated using '+' in a loop (SonarLint java:S1643)
* 11fa6df - refactor: consecutive AssertJ "assertThat" statements should be chained (SonarLint java:S5853)
* 03015af - refactor: chained AssertJ assertions should be simplified to the corresponding dedicated assertion (SonarLint java:S5838)
* e96d8be - refactor: lambdas should be replaced with method references (SonarLint java:S1612)
* 7baf520 - refactor: use the diamond operator ("<>") to reduce the verbosity of generics code (SonarLint java:S2293)
* d2d0ea1 - refactor: use Collections.emptyList() instead of Collections.EMPTY_LIST
* 1a62802 - refactor: re-order Java modifiers per conventions
* cabbe17 - docs: add contributors list to README
* 801c3af - release: 0.6.0
```

### CODE REVIEW

**Review by sazzad16 — APPROVED** [review]

**Comment by chayim** [comment]
Some comments:

1. We're generally removing contributors from READMEs everywhere, as it's a maintenance sink. On the other hand, the release drafter, already includes the contributors on the release. Can you remove from the readme.
2. CI was broken and not reporting back - I've fixed that - but note that CI now fails.Please have a look@bsbodden 

Question: Given the goal set of the JDK + how it works, but more importantly not having any OS specific code in here (other than the demos folder)... why run CI across the platforms?

**Comment by chayim** [comment]
On the merge side - once CI passes, and we're merged to master... master should properly publish snapshots to mavenhub. If that happens - we're good to use the drafter.

**Comment by bsbodden** [comment]
> Some comments:
> 
> 1. We're generally removing contributors from READMEs everywhere, as it's a maintenance sink. On the other hand, the release drafter, already includes the contributors on the release. Can you remove from the readme.

Ok

> 2. CI was broken and not reporting back - I've fixed that - but note that CI now fails.Please have a look@bsbodden
> 

Can you point me to the config that is running the build, the command should be:

`./mvnw clean verify` 

from the root folder of the project.
> Question: Given the goal set of the JDK + how it works, but more importantly not having any OS specific code in here (other than the demos folder)... why run CI across the platforms?

There is no OS specific code as far as I can tell, but don't know that is necessary to build on anything other than Linux/Mac OS/X

**Comment by bsbodden** [comment]
@chayim @sazzad16 the issue is that Docker needs to be added to the workflow. I'll try to do that and let you know.

**Review by guyroyse — APPROVED** [review]
LGTM

**Pull request merged**
